name: notify
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  provider: ^3.0.3
  url_launcher: ^5.5.0
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  firebase_messaging: ^6.0.16
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/icon/discord-grey.png
    - assets/icon/facebook-grey.png
    - assets/icon/inforge-grey.png
    - assets/icon/telegram-grey.png
    - assets/icon/web-grey.png
